name: Build and Push
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version (x.y.z)
        required: true
jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Change release branch
        run: |
          git branch release origin/release
          git fetch origin release:release
          git merge --ff-only release
          git checkout release

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Get yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Push release branch.
        run: |
          git config --global user.name "Yumis Developer"
          git config --global user.email "yumis-developer@users.noreply.github.com"
          git add .
          yarn version --new-version "${{ github.event.inputs.version }}"
          git push origin release
          git push --tags
